apiVersion: v1
kind: Service
metadata:
  name: petclinic-ui
  labels:
    app: petclinic-ui
spec:
  ports:
  - port: 7000
    name: http
  selector:
    app: petclinic-ui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic-ui
        version: v1
    spec:
      containers:
      - name: petclinic-ui
        image: gcr.io/ibesx-esa-sandbox-00f7f67a/petclinic-ui:1.0
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: petclinic-ui
spec:
  host: petclinic-ui
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: petclinic-ui-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: petclinic-ui
spec:
  hosts:
  - "*"
  gateways:
  - petclinic-ui-gateway
  http:
  - match:
    - uri:
      prefix: / 
    route:
    - destination:
        host: petclinic-ui
        port:
          number: 7000
--- 